# Generated by Django 2.2.5 on 2019-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('usename', models.CharField(max_length=100)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_notes', models.TextField()),
                ('AcessTo', models.TextField()),
                ('notAcessto', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('updation_date', models.DateTimeField()),
                ('history', models.TextField()),
                ('deletedstatuse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
