# Generated by Django 2.2.5 on 2019-09-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_data_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_data',
            old_name='notsharedwith',
            new_name='sharetoRW',
        ),
        migrations.RenameField(
            model_name='blog_data',
            old_name='sharedwith',
            new_name='sharetoReadOnly',
        ),
    ]
